import type { Metadata } from 'next'
import { Inter, Poppins } from "next/font/google"
import './globals.css'
import NavBar from './components/NavBar'
import FooterSection from './components/FooterSection'
import { Toaster } from './components/ui/toaster'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppin = Poppins({subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "700"]})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={poppin.className} >
      
      <main className="bg-white">
      <NavBar />
      {children}
      <Toaster />
      <div className="mt-[56px]">
        <FooterSection />
      </div>
    </main>
    
    </body>
    </html>
  )
}

